version: "2"

services:
  web:
    build: .
    environment:
      MYENV: env
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python3 manage.py migrate
  web_collectstatic:
    extends:
      service: web
    command: python3 manage.py collectstatic
  web_run:
    extends:
      service: web
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "80:80"
